### ISSUE TITLE
When changing link and refreshing page drops 404 error.

### ISSUE THREAD

**Issue by Maciejka1** [Blind2k/emailauthentication#1]
When you change link e. g. going from / to /profile and refresh, website drops 404 error. It happens because github doesn't know that there is such thing as react-router. It is fixed by adding _REDIRECTS on netlify but I don't know how to fix it when hosting on github.

**Comment by Blind2k** [comment]
Hi @Maciejka1, 
thank you for your post.
If I understand correctly, you tried this app on the [pages](https://blind2k.github.io/emailauthentication/)
I have looked into this issue. This error/bug/security gap is related to git pages. Downloading and executing the code on your IDE will not cause this issue.

However, if I understood this issue correctly, this has nothing to do with my code. Therefore, there is no problem with my repository. Only the way it is being shown on GitHub.
If I fail to understand you correctly, please reply with a proper and detailed answer. If you wish to solve this issue, I will gladly help you with the process of pulling and committing with Gitbash.
